import "./globals.css";
import { Inter } from "next/font/google";
import { MainConnector, PushSocketConnector } from "./(connectors)";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
	return (
		<html lang="en">
			<link rel="manifest" href="/manifest.json" />
			<body className={inter.className}>
				<Toaster position="top-center" reverseOrder={false} />
				<MainConnector />
				<PushSocketConnector />
				{children}
			</body>
		</html>
	);
};

export default RootLayout;
